#!/bin/sh
name=$(hostname)
echo "Machine name : $name"
kernel=$(cat /proc/version |cut -d" " -f1-3)
os=$(cat /etc/os-release | head -2)
echo "OS : $os and kernel version is $kernel"
ip=$(ip a | grep inet | grep enp0s8 | cut -d' ' -f6)
echo "IP : $ip"
ramtot=$(free -mh | grep Mem | cut -d' ' -f11)
ramava=$(free -mh | grep Mem | cut -d' ' -f46)
echo "RAM : $ramava RAM remaining of $ramtot"
disk=$(df -H | grep /dev/sda5 | cut -d' ' -f13)
echo "Disk : $disk remaining"
process=$(top -n 1 | head -12 | tail -5)
echo "Top 5 Process by RAM usage\n$process"
Listening_ports=$(ss -tulw | grep LISTEN)
echo "Listening ports : \n$Listening_ports"
CHAT=$(curl https://api.thecatapi.com/v1/images/search | jq -r ".[].url")
echo "Here's your random cat $CHAT"
